### ISSUE TITLE
popup keeps growing

### ISSUE THREAD

**Issue by matthiasg** [MarkoCen/angular-popup#5] opened 2015-09-04 15:19 UTC
i have an issue where the popup keeps growing due to an inconsistency in the width as set using style.width and the value returned via offsetWidth. They differ slightly causing the window to grow (and performance in general to suffer due to a feedback loop)

```
updateParentScopeOptions: function(options,element){
            var $element = element[0];
            options.position.left = $element.offsetLeft;
            options.position.top =  $element.offsetTop;

            if($element.getElementsByClassName('content')[0].style.display != 'none'){
                 options.width = $element.offsetWidth; // <-- offsetWidth is slightly larger than the originally set offset.width
                 options.height = $element.offsetHeight;
             }
        }
```

```
updateElementSize: function(...){
...
     $element.style.width = width;
...
```

**Comment by MarkoCen** [comment] 2015-09-08 21:24
@matthiasg 
Would you provide a plunker or jsBin example to demonstrate this issue more specifically?
I think the issue is due to `$element.offsetWidth` includes border width, but `options.width` not.
I would take a look when I get a chance
Thanks

**Comment by bstout** [comment] 2015-11-11 18:49
I too see this problem of the popup growing.

**Comment by dlebedynskyi** [comment] 2015-12-24 15:13
any news on this  bug? 
I would like to use this project but this bug prevents it .
plunker with fix
http://plnkr.co/edit/UBWRh6UYI6uho05r2E7C?p=preview. 
pull request below

**Comment by MarkoCen** [comment] 2016-01-15 17:01
#6 
fixed on this PR

**Closed as completed by MarkoCen** 2016-01-15 17:01 UTC
Labels: bug
